# vi: ft=ruby

require 'rbconfig'

VAGRANTFILE_API_VERSION = '2'

SERVER = 'dhcpsrv'
CLIENT = 'dhcpcln'
NETWORK = 'dhcptestnet'
GROUP = '/' + NETWORK
SERVER_IP = '192.168.222.2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'centos71-nocm'
  config.vm.box_url = 'https://tinfbo2.hogent.be/pub/vm/centos71-nocm-1.0.16.box'
  config.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--groups', GROUP]
  end

  config.vm.define SERVER do |node|
    node.vm.hostname = SERVER
    node.vm.network :private_network,
      ip: SERVER_IP,
      virtualbox__intnet: NETWORK

    node.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'test.yml'
    end
  end

# The definition of the client is commented out because adding the second
# network interface (with dhcp) also appears to disable the NAT interface,
# effectively making the VM inaccessible.

#  config.vm.define CLIENT do |node|
    #node.vm.hostname = CLIENT

    #node.vm.network :private_network,
      ##auto_config: false,
      #type: :dhcp,
      #virtualbox__intnet: NETWORK
#  end
end

