# roles/dhcp/handlers/main.yml
---

- name: restart dhcp
  service:
    name: "{{ dhcp_service }}"
    state: "{{ (dhcp_global_server_state | default('started') == 'started') | ternary('restarted', 'stopped') }}"

- name: restart apparmor
  service:
    name: apparmor
    state: restarted

- name: restart prometheus exporter
  systemd:
    daemon_reload: yes 
    name: dhcp-stats-prometheus-exporter
    state: restarted
    enabled: yes

- name: restart firewall
  systemd:
    daemon_reload: yes 
    name: firewalld
    state: restarted
    enabled: yes
